
set(MYISA_SRC
	${CMAKE_CURRENT_SOURCE_DIR}
)

set(MYISA_HEAD
	${CMAKE_CURRENT_SOURCE_DIR}

)

#add_library(myisa ${MYISA_SRC} ${MYISA_HEAD})

#target_link_libraries(myisa PRIVATE device_commons)
#target_include_directories(myisa PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${PROJECT_SOURCE_DIR}/device_commons)

